### ISSUE TITLE
virtualBox Support

### ISSUE THREAD

**Issue by zez3** [extremenetworks/Virtual_VOSS#3]
Can this be achieved with VirtualBox instead of VMWare Player?

**Comment by stewilliams-extr** [comment]
Sorry it took so long to respond.  You should be able to convert the qcow2 to VirtualBox using the [quemu-img](https://www.qemu.org/docs/master/interop/qemu-img.html) tool.

qemu-img convert -O vdi <file_name>.qcow2 <file_name>.vdi
