### ISSUE TITLE
VOSS 8.1.5 - Fabric Data Plane - KO

### ISSUE THREAD

**Issue by Paracetamole** [extremenetworks/Virtual_VOSS#4]
**Describe the bug**
In basic fabric environment, VPC4 and VPC5 doesn't ping each other.
IS-IS and SPBM are OK. But we can't ping not even the loopback (VSP1<=>3)

**To Reproduce**
Basic configuration of Extreme Fabric Infrastructure (see backups configuration)

**Expected behavior**
VPC4 (192.168.1.10) must be able to ping VPC5 (192.168.1.20)

**Environment**
Eve-NG : 3* VOSS 8.1.5 (VSP1/3 = BEB et VSP2 = BCB) + 2 VPC (basic computer)

VPC4 = 192.168.1.10/24
VSP 1 (BEB1) = 10.10.10.1/32 (loopback) + 192.168.100.1/24 (vlan 100 mgmt vlan for fabric)
VSP 2 (BEC) = 10.10.10.10/32 (loopback) + 192.168.100.10/24 (vlan 100 mgmt vlan for fabric)
VSP 3 (BEB2) = 10.10.10.2/32 (loopback) + 192.168.100.2/24 (vlan 100 mgmt vlan for fabric)
VPC5 = 192.168.1.20/24

**Screenshots**
_Infrastructure_
![fabricpng](https://user-images.githubusercontent.com/52856940/86139269-ceefe600-baef-11ea-9b1f-f990a5ccf07b.png)

_VSP1-BEB1_
![MicrosoftTeams-image](https://user-images.githubusercontent.com/52856940/86143826-365c6480-baf5-11ea-94f3-16ed9623dc4b.png)

_VSP2-BEC_
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/52856940/86143834-38bebe80-baf5-11ea-9d13-3c0d3ec697dc.png)

_VSP3-BEB2_
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/52856940/86143837-39efeb80-baf5-11ea-8aeb-fa22fe371c55.png)

**Backups Configuration**
[vsp1.txt](https://github.com/extremenetworks/Virtual_VOSS/files/4852558/vsp1.txt)
[vsp2.txt](https://github.com/extremenetworks/Virtual_VOSS/files/4852560/vsp2.txt)
[vsp3.txt](https://github.com/extremenetworks/Virtual_VOSS/files/4852562/vsp3.txt)

**Comment by thijsvdc** [comment]
Hi @Paracetamole , dataplane was not implemented in Virtual VOSS 7.1 and 8.1. Did someone inform you that it should have been added in v8.1.5? I could not find anything related to dataplane in v8.1.5, so I'm afraid it's still not implemented...

**Comment by lvmv5** [comment]
Spoke to Extremenet SE and I actually requested that they speed up the release of a Dataplane version. In my scenario specifically I need it to test the XMC as the central management and provisioning of L2 & L3 VSN as well as edge FA/FlexUNI provisioning. Told them that there's a business case as less netadmin/engineers are going into the office or have access to the labs. They did confirm current versions including 8.1.5 do not support data plane. Will chime in if there's a release coming soon.

**Comment by Melhuig** [comment]
Thanks for the information, @lvmv5 ;) I hope the release will come soon because I really need to have a lab !

**Comment by MarlonScheid** [comment]
The XA1400 GNS3 Image has dataplane support. The XA1400 software is based on VOSS. Everything is working except Fabric Attach (FA) and vIST, which is currently not supported on the XA1400. You can ask your local SE for the image.

**Comment by erosxy** [comment]
A new voss (VOSSGNS3.8.2.0.0.GA) image has been added  5 days ago. 
i tested and i think the data plan is now implemented. 
i setup a very basic lab with 2 voss 8.2 along with user vlan with 2 ip addresses and the peers are able to ping each other which was not the case in the before.

i hope that connecetivity through out VSN 2&3 are also functional. if it's so, it would be a great improvement !!!

**Comment by Melhuig** [comment]
@erosxy Thanks for your comment !
I have not managed to set up a simple and working lab. My 2 hosts do not ping each other within the same network.

```
        +-----+    +-------+    +-------+    +-------+    +-----+
        | PC1 |----| VSP11 |----| VSP22 |----| VSP33 |----| PC2 |
        +-----+    +-------+    +-------+    +-------+    +-----+
192.168.10.1/24                                           192.168.10.2/24
```

(VLAN 10 - I-SID 100110)

On the other hand, everything seems to be OK regarding the control-plane, as before :

(VSP2)
```
VSP-22:1#show isis spbm i-sid all        
************************************************************************************
                Command Execution Time: Thu Oct 22 09:22:50 2020 UTC
************************************************************************************

====================================================================================================
                                 SPBM ISID INFO
====================================================================================================
ISID      SOURCE NAME   VLAN   SYSID                TYPE         HOST_NAME         ISID NAME
----------------------------------------------------------------------------------------------------
100110    0.00.01       4052   00bb.0031.0001       discover     VSP-11            ISID-100110
100110    0.00.03       4052   00bb.0031.0003       discover     VSP-33            ISID-100110
[...]
```

The only things which actually works is a ping between PC1 and VSP11 (or PC2 and VSP33)...

**Comment by erosxy** [comment]
Thanks a lot Melhuig.
It's  pity as actually i tested a basic ping without VSNL2 so unfortunately DP  is still not implemented ; it's very frustrating !

**Comment by stewilliams-extr** [comment]
Hello everyone,

I agree that the data plane functionality would be great to have, and I've let the proper team know of the requests/post made here.  As of now there is no data plane functionality currently planned for the VOSS VM.  If you haven't already, you can make a formal feature request with your local sales team.

--Stephen
