### ISSUE TITLE
Adapters GNS3 Config no matching console config

### ISSUE THREAD

**Issue by RANDW0LF** [extremenetworks/Virtual_VOSS#6]
Not sure what I am doing wrong, but setting  Configure > Network > Adapters in GNS3 is not then reflected once consoled in. eg no mater the number of Adapters set, config shows 1/1-40 10gb, 1/41-42 40gb and 2/1-2/40, 2/41-42 40gb.
Cheers

**Comment by ZdenekPala** [comment]
I am not the expert, but I believe the port speed is hardcoded and can not be changed

**Comment by RANDW0LF** [comment]
sorry I am refering to the port numbers in GNS3 vs what actually appars when you Console into the device.
eg. GNS3 9 Network Adapters, but then in the Console it has 1/1-1/42 and 2/1-2/42. None of them showing as UP.

**Comment by stewilliams-extr** [comment]
Hi RANDW0LF,

To be clear.  You are using the GNS3 template file to add it to GNS3?

The port name format should be:
"port_name_format": "1/{port1}",

https://github.com/extremenetworks/Virtual_VOSS/raw/master/VOSSGNS3.8.X.gns3a

**Comment by RANDW0LF** [comment]
Thankyou for the reply, but again, this is nothing at all to do with port speeds, I was only including the port types.
I am refering to port numbers in GNS3 vs what is showing in the console. Please see below:

![VOSSGNS3](https://user-images.githubusercontent.com/71426335/126858213-0e7d2cfb-afdc-4612-97e5-54bfe60fd070.png)
![VOSSConsole](https://user-images.githubusercontent.com/71426335/126858214-35388ce7-5180-440e-aa81-c4f0a9de067b.png)

**Comment by marlon82** [comment]
Hi,Only the ports 1/1  to 1/8 are accessible from gns3. All other ports not. The images of this node is based on a vsp8200 which this amount of ports. But only the first 8 ports and the most ports are usable in gns3.RegardsMarlonAm 24.07.2021 07:17 schrieb RANDW0LF ***@***.***>:
Thankyou for the reply, but again, this is nothing at all to do with port speeds, I was only including the port types.
I am refering to port numbers in GNS3 vs what is showing in the console. Please see below:

**Comment by RANDW0LF** [comment]
> Hi, Only the ports 1/1  to 1/8 are accessible from gns3. All other ports not. The image of this node is based on a vsp8200 which has the amount of ports. But only the first 8 ports and the mgmt port are usable in gns3. Adapter 0 is mapped to mgmt port ( int mgmt mgmt) Adapter 1 to 8 is mapped to Ports 1/1 to 1/8. And keep in mind only the controlplane is working but not the data plane. So you can not connect clients and ping through the virtual voss device! Regards Marlon

Thankyou, understood.
