### ISSUE TITLE
Unable installing VOSS VM

### ISSUE THREAD

**Issue by ErikaLVargasC** [extremenetworks/Virtual_VOSS#7]
I am following the article https://github.com/extremenetworks/Virtual_VOSS/blob/master/GNS3_VOSS-VM_Guide.md to install a VOSS VM however i get a problem:

1. On 7 Step (Step 7: Setting up GNS3)  first Point i see the options: Run Appliances in a virtual machine, Run Appliances on my locacl Computer, Run Appliances on a remote server. But i don´t get any "Run modern IOS"

i am using GNS3 2.2.31 version

Many thanks if you can support me on it.

**Comment by stewilliams-extr** [comment]
The guide is written for use of the GNS3 VM.  Select "Run Appliances in a virtual machine"

**Comment by ErikaLVargasC** [comment]
@stewilliams-extr step 7. 4 solved

**Comment by stewilliams-extr** [comment]
Added the extra option "Run Appliances in a virtual machine".

https://github.com/extremenetworks/Virtual_VOSS/commit/4b3bfbd96bd11dc4e40838addf62f6286f24055f
